# Generated by Django 4.2.4 on 2023-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
