# Generated by Django 4.2.5 on 2023-09-14 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_projectsmodel_status'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.CharField(max_length=200)),
                ('Region', models.CharField(max_length=200)),
                ('Salesman', models.CharField(max_length=200)),
                ('Client', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=200)),
                ('Subcategory', models.CharField(max_length=200)),
                ('SKU', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Starting', models.CharField(max_length=200)),
                ('Period', models.CharField(max_length=200)),
                ('Year', models.CharField(max_length=200)),
                ('Periods', models.CharField(max_length=200)),
                ('Per', models.CharField(max_length=200)),
                ('Cycle', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
