# Generated by Django 4.2.5 on 2023-09-14 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_historicaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldata',
            old_name='family',
            new_name='Family',
        ),
    ]
