# Generated by Django 4.2.5 on 2023-09-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_rename_family_historicaldata_family'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldata',
            old_name='Cycle',
            new_name='PeriodsPerCycle',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='Per',
            new_name='PeriodsPerYear',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='Period',
            new_name='StartingPeriod',
        ),
        migrations.RenameField(
            model_name='historicaldata',
            old_name='Periods',
            new_name='StartingYear',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Starting',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='Year',
        ),
    ]
