# Generated by Django 4.2.5 on 2023-09-14 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_rename_cycle_historicaldata_periodspercycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldata',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='project',
        ),
        migrations.RemoveField(
            model_name='historicaldata',
            name='user',
        ),
    ]
