# Generated by Django 4.2.4 on 2023-12-19 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=200, unique=True)),
                ('pred_p', models.IntegerField()),
                ('test_p', models.IntegerField()),
                ('replace_negatives', models.BooleanField(default=False)),
                ('seasonal_periods', models.IntegerField(blank=True, null=True)),
                ('max_historical_date', models.DateField(blank=True, null=True)),
                ('final_data_pred', models.JSONField(blank=True, null=True)),
                ('data_year_pred', models.JSONField(blank=True, null=True)),
                ('error_last_twelve_periods', models.FloatField(blank=True, null=True)),
                ('error_last_period', models.FloatField(blank=True, null=True)),
                ('error_abs', models.FloatField(blank=True, null=True)),
                ('error_type', models.CharField(max_length=250)),
                ('predictions_table_name', models.CharField(blank=True, max_length=250, null=True)),
                ('url_predictions', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_params', models.JSONField(default=dict)),
                ('models', models.JSONField(default=list)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filerefmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
