# Generated by Django 4.2.4 on 2023-09-16 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSelectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_mode', models.CharField(max_length=200)),
                ('top_down_dims', models.CharField(max_length=200)),
                ('forecast_dims', models.CharField(max_length=200)),
                ('replace_outliers', models.CharField(max_length=200)),
                ('interpolate_negatives', models.CharField(max_length=345)),
                ('interpolate_zeros', models.CharField(max_length=345)),
                ('interpolation_methods', models.CharField(max_length=345)),
                ('outliers_detection', models.CharField(max_length=345)),
                ('missing_values_t', models.CharField(max_length=345)),
                ('pex_variables', models.CharField(max_length=345)),
                ('mapes100', models.CharField(max_length=345)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filerefmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
