# Generated by Django 4.2.4 on 2023-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastscenario',
            name='models',
            field=models.JSONField(default=list),
        ),
    ]
