# Generated by Django 4.2.4 on 2023-09-26 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_name', models.CharField(max_length=200, unique=True)),
                ('pred_p', models.IntegerField()),
                ('test_p', models.IntegerField()),
                ('run_mode', models.CharField(max_length=200)),
                ('top_down_dimensions', models.CharField(max_length=200)),
                ('optimized_metrics', models.CharField(max_length=200)),
                ('forecast_dims', models.CharField(max_length=200)),
                ('replace_outliers', models.CharField(max_length=200)),
                ('interpolate_negatives', models.CharField(max_length=345)),
                ('interpolate_zeros', models.CharField(max_length=345)),
                ('interpolation_methods', models.CharField(max_length=345)),
                ('outliers_detection', models.CharField(max_length=345)),
                ('missing_values_t', models.CharField(max_length=345)),
                ('pex_variables', models.CharField(max_length=345)),
                ('models', models.TextField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filerefmodel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DataSelectors',
        ),
    ]
