# Generated by Django 4.2.4 on 2023-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastscenario',
            name='additional_params',
            field=models.JSONField(default=dict),
        ),
    ]
